### ISSUE TITLE
It doesnt inject into the game using sharp mono injector

### ISSUE THREAD

**Issue by ItsyeBitsy** [sadece1eren/Content-Warning-Cheat#3]
Status: Injection failed: mono_ class_from_name() returned NULL

**Comment by ItsyeBitsy** [comment]
![image](https://github.com/sadece1eren/Content-Warning-Cheat/assets/142978395/ea07c48e-8c31-4f54-88d8-187af5ab31d3)
![image](https://github.com/sadece1eren/Content-Warning-Cheat/assets/142978395/f8f7dee2-ad75-4a14-a4a6-851abd00f843)

**Comment by sadece1eren** [comment]
Namespace is wrong. It needs to be ContentWarningCheat 

![image](https://github.com/sadece1eren/Content-Warning-Cheat/assets/60568960/2676c99c-0156-4a4f-a62e-b5dc9406e6b7)

Have Fun.
